# Generated by Django 3.2.14 on 2022-07-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('L', 'Lost'), ('F', 'Found'), ('M', 'Matched')], max_length=2),
        ),
    ]
