# Generated by Django 3.2.14 on 2022-07-21 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220721_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('Lost', 'L'), ('Found', 'F'), ('Matched', 'M')], max_length=10),
        ),
    ]
