# Generated by Django 3.2.14 on 2022-07-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_pet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(default='', max_length=10, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='color',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('lost', 'lost'), ('found', 'found'), ('matched', 'matched')], max_length=10),
        ),
    ]
