# Generated by Django 3.2.14 on 2022-08-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_pet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.TextField(default=''),
        ),
    ]
