# Generated by Django 3.2.14 on 2022-08-11 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_pet_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='color',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='location',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='name',
        ),
    ]
