# Generated by Django 4.0.6 on 2022-08-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220811_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='latitude',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pet',
            name='longitude',
            field=models.TextField(default=''),
        ),
    ]
