# Generated by Django 4.0.6 on 2022-09-11 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_pet_latitude_pet_longitude'),
        ('api', '0011_auto_20220829_1328'),
    ]

    operations = [
    ]
