# Generated by Django 4.0.6 on 2022-10-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_merge_20220911_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='face_features',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pet',
            name='latitude',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pet',
            name='longitude',
            field=models.TextField(blank=True, default=''),
        ),
    ]
